create table t(
    a int,
    b int default 1,
    c int generated always as (1) stored,
    d int generated always as identity,
    e int generated by default as identity
);


create table "public"."gen" (
    "adding" integer,
    "removing" integer generated always as (1) stored
);


create table identchanges (
    c int default 77,
    d int generated always as identity,
    e int generated by default as identity,
    f int generated always as identity
);