create table t2(
    a int,
    b int default 1,
    c int generated always as (1) stored,
    d int generated always as identity,
    e int generated by default as identity
);

create table "public"."gen" (
    "adding" integer generated always as (1) stored,
    "removing" integer
);


create table identchanges (
    c int generated by default as identity,
    e int generated always as identity,
    d int generated by default as identity,
    f int
);