drop table "public"."t";

create table "public"."t2" (
    "a" integer,
    "b" integer default 1,
    "c" integer generated always as (1) stored,
    "d" integer generated always as identity not null,
    "e" integer generated by default as identity not null
);


alter table "public"."gen" drop column "adding";

alter table "public"."gen" add column "adding" integer generated always as (1) stored;

alter table "public"."gen" alter column "removing" drop expression;

alter table "public"."identchanges" alter column "c" drop default;

alter table "public"."identchanges" alter column "c" set not null;

alter table "public"."identchanges" alter column "c" add generated by default as identity;

alter table "public"."identchanges" alter column "d" set generated by default;

alter table "public"."identchanges" alter column "e" set generated always;

alter table "public"."identchanges" alter column "f" drop identity;

alter table "public"."identchanges" alter column "f" drop not null;
